FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY app.py .env ./
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "--workers", "4", "app:app"]
